name: wiki_frame
description: "Listens for a search phrase from the user, queries Wikipedia and returns an extract for display in Frame"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.11
  http: ^0.13.5
  image: ^4.2.0
  logging: ^1.2.0
  speech_to_text: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/frame_app.lua
    - assets/frame_app.min.lua
